language: node_js
sudo: false
node_js:
- 6
- 8
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ ! -z ${encrypted_ac3aacad7ba8_key} ] &&
  openssl aes-256-cbc -K $encrypted_ac3aacad7ba8_key
  -iv $encrypted_ac3aacad7ba8_iv -in secrets.tar.enc -out test/resources/secrets.tar
  -d || true'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ ! -z ${encrypted_ac3aacad7ba8_key} ]
  && cd test/resources/ && tar xvf secrets.tar
  && cd ../.. || true'
- npm install -g typescript
script:
- tsc
- npm run test-unit-travis || travis_terminate 1
- npm run test-integration-travis || node scripts/report_integration_test.js || travis_terminate 1
- npm run check-packages
- sh scripts/typedoc/generate_typedoc.sh
after_success:
- npm run report-coverage
- scripts/jsdoc/publish.sh
deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 8
